"""add cloudinary public ids

Revision ID: f515fe1ed5ab
Revises: a79d78746d51
Create Date: 2026-07-21 13:07:57.502430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f515fe1ed5ab'
down_revision: Union[str, Sequence[str], None] = 'a79d78746d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('thumbnail_public_id', sa.String(length=500), nullable=True))
    op.add_column('blogs', sa.Column('cover_image_public_id', sa.String(length=500), nullable=True))
    op.drop_column('blogs', 'canonical_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('canonical_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'cover_image_public_id')
    op.drop_column('blogs', 'thumbnail_public_id')
    # ### end Alembic commands ###
